version: 2

models:
  - name: int_local_bike__order_items_enriched
    description: "This model aims at enriching stg_local_bike__order_items model since we need to recalculate some indicators for each row "
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item. Concatenation of order_id and item_id"
        tests:
          - unique
          - not_null

      - name: order_date
        description: "Date when the order was placed by the customer."
        tests:
          - not_null

      - name: customer_id
        description: "Foreign key linking the feedback to the corresponding customer"
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_sales_database__orders
              to: ref('stg_local_bike__customers')
              field: customer_id

      - name: order_id
        description: "Foreign key linking the item to the corresponding order."
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__orders_item
              to: ref('stg_local_bike__orders')
              field: order_id

      - name: order_status
        description: "Current status of the order (1: pending, 2: processing, 3: completed, 4: cancelled)."
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
              quote: false

      - name: required_date
        description: "Requested delivery date specified for the order."

      - name: shipped_date
        description: "Date when the order was shipped to the customer. Null if the order has not been shipped yet."

      - name: store_id
        description: "Foreign key linking the order to the store where it was placed."
        tests:
        - not_null
        - relationships:
            name: store_id_foreign_key_in_stg_local_bike__orders
            to: ref('stg_local_bike__stores')
            field: store_id

      - name: staff_id
        description: "Foreign key linking the order to the staff member responsible for handling it."
        tests:
        - not_null
        - relationships:
            name: staff_id_foreign_key_in_stg_local_bike__orders
            to: ref('stg_local_bike__staffs')
            field: staff_id

      - name: full_name
        description: "Concatenation of first name and last name of staff"

      - name: active
        description: "Indicator if the staff member is active (1) or inactive (0)."
        tests:
        - accepted_values:
              values: [0, 1]
              quote: false  

      - name: item_id
        description: "Identifier for the item line within the order. Can be used to order items sequentially within the same order."
        tests:
          - not_null

      - name: product_id
        description: "Foreign key linking the item to the specific product."
        tests:
          - not_null
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__products')
              field: product_id
      
      - name: stock
        description: "Stock of a specific product available in each store"

      - name: quantity
        description: "Number of units of the product ordered in this order item."
        tests:
          - not_null

      - name: list_price
        description: "Unit price of the product at the time of order."
        tests:
          - not_null

      - name: discount
        description: "Discount applied to this item, expressed as a decimal fraction (e.g., 0.1 for 10% off)."

      - name: discounted_amount
        description: "Amount of the discount."

      - name: amount_without_discount
        description: "Total amount calculated as quantity multiplied by the list price."
      
      - name: amount_with_discount
        description: "Total amount calculated as quantity multiplied by the discounted price."

      - name: brand_id 
        description: "Foreign key to brand_id in stg_local_bike__brands, unique identifier of the brand."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__brands')
              field: brand_id
      
      - name: brand_name
        description: "Name of the brand"
        tests:
          - not_null
      
      - name: category_id
        description: "Unique identifier for each category"
        tests:
          - relationships:
              to: ref('stg_local_bike__categories')
              field: category_id
      
      - name: category_name
        description: "Name of the category"

      - name: model_year
        description: "Year when product has been created"
  
  - name: int_local_bike__products_enriched 
    description: "This model consolidates all product-related information in a single place"
    columns: 
      - name: product_id 
        description: "Foreign key linking the item to the specific product."
        tests:
          - not_null
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__products')
              field: product_id

      - name: brand_id 
        description: "Foreign key to brand_id in stg_local_bike__brands, unique identifier of the brand."
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike__brands')
              field: brand_id
      
      - name: brand_name
        description: "Name of the brand"
        tests:
          - not_null
      
      - name: category_id
        description: "Unique identifier for each category"
        tests:
          - relationships:
              to: ref('stg_local_bike__categories')
              field: category_id
      
      - name: category_name
        description: "Name of the category"

      - name: model_year
        description: "Year when product has been created"
      
      - name: list_price
        description: "Price of a product."
  
  - name: int_local_bike__orders_enriched
    description: "This model consolidates all informations related to order"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null
          
      - name: customer_id
        description: "Foreign key linking the feedback to the corresponding customer"
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_sales_database__orders
              to: ref('stg_local_bike__customers')
              field: customer_id

      - name: order_status
        description: "Current status of the order (1: pending, 2: processing, 3: completed, 4: cancelled)."
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
              quote: false

      - name: order_date
        description: "Date when the order was placed by the customer."
        tests:
        - not_null

      - name: required_date
        description: "Requested delivery date specified for the order."

      - name: shipped_date
        description: "Date when the order was shipped to the customer. Null if the order has not been shipped yet."

      - name: store_id
        description: "Foreign key linking the order to the store where it was placed."
        tests:
        - not_null
        - relationships:
            name: store_id_foreign_key_in_stg_local_bike__orders
            to: ref('stg_local_bike__stores')
            field: store_id
      
      - name: store_name
        description: "Name of the store."

      - name: city
        description: "City where the store is located."

      - name: state
        description: "State where the store is located."

      - name: staff_id
        description: "Foreign key linking the order to the staff member responsible for handling it."
        tests:
        - not_null
        - relationships:
            name: staff_id_foreign_key_in_stg_local_bike__orders
            to: ref('stg_local_bike__staffs')
            field: staff_id
      
      - name: full_name
        description: "Concatenation of first name and last name of staff"

      - name: active
        description: "Indicator if the staff member is active (1) or inactive (0)."
        tests:
        - accepted_values:
              values: [0, 1]
              quote: false  

      - name: nb_distinct_items
        description: "Number of distinct items per order"
      
      - name: nb_distinct_products
        description: "Number of distinct products per order"
      
      - name: quantity
        description: "Total number of items"

      - name: total_amount
        description: "Total order amount calculated from the list price."
      
      - name: total_amount_discounted
        description: "Total order amount calculated from the discounted price."
      
      - name: amount_discounted
        description: "Discount amounted for the order"
      
