version: 2

models:
  - name: stg_local_bike__customers
    description: "This model contains detailed informations about customers"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: phone
        description: "Phone number of the customer"
      - name: email
        description: "Email of the customer"
      - name: street
        description: "Street of the customer"
      - name: city
        description: "City of the customer"
      - name: state
        description: "State of the customer"
      - name: zip_code
        description: "Zip code of the customer"

  - name: stg_local_bike__orders
    description: "This models contains detailed informations about orders"
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order"
        tests:
          - unique
          - not_null
          
      - name: customer_id
        description: "Foreign key linking the feedback to the corresponding customer"
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_sales_database__orders
              to: ref('stg_local_bike__customers')
              field: customer_id

      - name: order_status
        description: "Current status of the order (1: pending, 2: processing, 3: completed, 4: cancelled)."
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
              quote: false

      - name: order_date
        description: "Date when the order was placed by the customer."
        tests:
        - not_null

      - name: required_date
        description: "Requested delivery date specified for the order."

      - name: shipped_date
        description: "Date when the order was shipped to the customer. Null if the order has not been shipped yet."

      - name: store_id
        description: "Foreign key linking the order to the store where it was placed."
        tests:
        - not_null
        - relationships:
            name: store_id_foreign_key_in_stg_local_bike__orders
            to: ref('stg_local_bike__stores')
            field: store_id

      - name: staff_id
        description: "Foreign key linking the order to the staff member responsible for handling it."
        tests:
        - not_null
        - relationships:
            name: staff_id_foreign_key_in_stg_local_bike__orders
            to: ref('stg_local_bike__staffs')
            field: staff_id

  - name: stg_local_bike__orders_item
    description: "This model contains details about each item in an order"
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item. Concatenation of order_id and item_id"
        tests:
          - unique
          - not_null

      - name: order_id
        description: "Foreign key linking the item to the corresponding order."
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__orders_item
              to: ref('stg_local_bike__orders')
              field: order_id

      - name: item_id
        description: "Identifier for the item line within the order. Can be used to order items sequentially within the same order."
        tests:
          - not_null

      - name: product_id
        description: "Foreign key linking the item to the specific product."
        tests:
          - not_null
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__products')
              field: product_id

      - name: quantity
        description: "Number of units of the product ordered in this order item."
        tests:
          - not_null

      - name: list_price
        description: "Unit price of the product at the time of order."
        tests:
          - not_null

      - name: discount
        description: "Discount applied to this item, expressed as a decimal fraction (e.g., 0.1 for 10% off)."

  - name: stg_local_bike__staffs
    description: "This model contains detailed information about staff members in the local bike stores."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member."
        tests:
          - unique
          - not_null

      - name: first_name
        description: "First name of the staff member."
        tests:
          - not_null

      - name: last_name
        description: "Last name of the staff member."
        tests:
          - not_null

      - name: email
        description: "Email address of the staff member."
        tests:
          - not_null
          - unique

      - name: phone
        description: "Phone number of the staff member."

      - name: active
        description: "Indicator if the staff member is active (1) or inactive (0)."
        tests:
          - accepted_values:
              values: [0, 1]
              quote: false

      - name: store_id
        description: "Foreign key linking the staff member to the store they work at."
        tests:
          - not_null
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike__staffs
              to: ref('stg_local_bike__stores')
              field: store_id

      - name: manager_id
        description: "Identifier of the manager for this staff member. Can be null if the staff member has no manager."

  - name: stg_local_bike__stores
    description: "This model contains detailed information about stores"
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
          - unique
          - not_null

      - name: store_name
        description: "Name of the store."

      - name: phone
        description: "Phone number of the store."

      - name: email
        description: "Email of the store."

      - name: street
        description: "Street address of the store."

      - name: city
        description: "City where the store is located."

      - name: state
        description: "State where the store is located."

      - name: zip_code
        description: "Zip code of the store."



    